name = "edge-sub"
compatibility_date = "2026-10-10"

main = "edge-sub.yopityu56.workers.dev/index.js"
site.bucket = "./"

kv_namespaces = [
    { binding = "EdgeSubDB", id = "c4c7c8ca-b226-4a23-b665-a7768e9093f5" },
]
